### ISSUE TITLE
Failed to communicate with device

### ISSUE THREAD

**Issue by ulrischa** [Drolla/WavePlus_Bridge#4]
When I Run `sudo /opt/waveplus_bridge/waveplus_bridge.py \
       --config /opt/waveplus_bridge/waveplus_bridge.yaml \
       --log ""
`
I get the Error: Failed to communicate with device ******
And Could not find device

**Comment by Drolla** [comment]
Is this the only error message you have received, @ulrischa? Otherwise, could you please add the full log?

A few questions:
- What is the platform (which Raspberry Pi version)?
- Have you enabled Bluetooth?
- Were you already able to connect to the WavePlus device from your Raspberry Pi (with another application)?
- Are you running the application as admin/root, or as normal user?
- What Python and BluePy versions are you using?
- How far away is your Raspberry Pi from your WavePlus device?

Could you please also send the information from your configuration file (waveplus_bridge.yaml) that is relevant for the connection (period, sn, port). Please don't send eventual private data (email, password, etc).

Finally, if you keep the the application running, are you getting notified that the connection can be established, or is the connection never established?

**Comment by ulrischa** [comment]
Hi, here some information:
Platform: Raspberry Pi 4 4gb
Bluetooth enable
Connection to Wave Plus works with the official reader
Run command as pi user wirh sudo
Beweist version of python and bluepy (as in the install instruction)
The raspberry is approx. 10m away, but enough for the official reader

The other information tomorrow

**Comment by ulrischa** [comment]
Works like a charm. It was too far away from the waveplus. Strange because with the official reader script it worked

**Comment by Drolla** [comment]
OK, happy to hear that it works now.
I do not see any reason why the distance to a WavePlus device would be smaller with this Bridge than with the official reader script, since both solutions use the same communication methods. However if you have a confirmation that the distance is smaller with this Bridge, please let me know. I will run then some investigations.

**Comment by ulrischa** [comment]
Yes I have tested it without moving the pi or the airthings wave plus. And the official reader seems to work for a longer distance.
